//
//  BatteryDrawing.h
//  New Image
//
//  Created by Thomas Denney on 06/10/2013
//  Copyright 2013 Thomas Denney
//  This code was generated by Opacity Express. You may use or modify it in any way.
//

#include <CoreGraphics/CoreGraphics.h>

extern const CGFloat kBatteryDrawingFunctionWidth;
extern const CGFloat kBatteryDrawingFunctionHeight;

extern void BatteryDrawingFunction(CGContextRef context, CGRect bounds, CGFloat Percentage);
